### ISSUE TITLE
Support of plain HTTP proxy

### ISSUE THREAD

**Issue by kvendingoldo** [tofuutils/tenv#138]
**Describe the solution you'd like**
tfswitch support `--mirror` command that can be used with local proxy. E.g.:  `["tfswitch", "--mirror", "https://localhost-archive/mirror/terraform", "--bin", f"{os.getcwd()}/bin/terraform"]`

Looks like that it should work via TFENV_REMOTE, but we have to check HTTP compatibility.

**Comment by kvendingoldo** [comment]
Found in https://github.com/MatthewJohn/terrareg/issues/42

**Comment by dvaumoron** [comment]
Setting a value for on of the  `<TOOL>_REMOTE` env var change the behavior of **tenv**, because it is considered that the user will access an http proxy to download artifact.

However **tenv** still call api (github or hashicorp) to list those artifact. do you think it would be better to change the default proxy mode ? (list from the proxy when `<TOOL>_LIST_MODE` is not set to "api")

**Comment by dvaumoron** [comment]
Ok
