### ISSUE TITLE
AUR: ERROR: tenv-bin is not available for the 'x86_64' architecture.

### ISSUE THREAD

**Issue by muchgitsuchwow** [tofuutils/tenv#174]
**Describe the bug**
https://github.com/tofuutils/tenv/pull/173 introduced a new PKGBUILD on AUR. This new PKGBUILD supports only:

```
arch=('aarch64' 'i686')
```

**Expected behavior**
AUR `tenv-bin` package is available for all supported archs again, like `x86_64`.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by kvendingoldo** [comment]
@muchgitsuchwow thank you for reporting. I'm working on this issue, hope that it will be fixed today

**Comment by kvendingoldo** [comment]
Trying to find what's wrong with goreleaser; 
Based on that I see that we have to had x86_64, 386 packages: https://github.com/goreleaser/goreleaser/blob/8ad6b3479bc9999f0567cd84c33a247b5d17d98e/internal/pipe/aur/aur.go#L267

**Comment by kvendingoldo** [comment]
Dunno why goreleaser decided to use i686 instead of pure 386. @clee231 @muchgitsuchwow guys, do you think that it's a problem for 386 users?
```
	case "386":
		return "i686"
```

**Comment by clee231** [comment]
@kvendingoldo 
I think it is fine to use `i686`. It's a newer revision of the `x86` platform and should be backwards compatible with `i386`. My understanding is that each newer revision supports additional instruction sets. They don't remove usually remove opcodes after introduction.

At least for ArchLinux, the latest release of the 32-bit variant only mentions support for `i686`, so that may be why goreleaser is making that switch.

I took some time to also take a look at the executables being generated in the latest `v2.1.5` release and they are all built for the `i386` platform, so even if someone tried to force install on an older platform, it should work still.

![Screenshot_20240617_054810_GitHub.jpg](https://github.com/tofuutils/tenv/assets/1387910/9f806dfe-f903-44c1-87a5-eeedd7d91714)

**Comment by kvendingoldo** [comment]
@clee231 @muchgitsuchwow looks like it works now, please check it
<img width="630" alt="Screenshot 2024-06-17 at 16 44 14" src="https://github.com/tofuutils/tenv/assets/11614750/b7ee75f3-0dec-40a7-a704-1e37dc48bc18">

**Comment by clee231** [comment]
I was able to test it on my machine. I was able to install `v2.1.6` with no issue now on `x86_64` using the latest PKGBUILD.
Thanks for addressing this so quickly, @kvendingoldo !

**Comment by kvendingoldo** [comment]
@clee231 I've added you to AUR as contributor/maintainer. 
Will wait for @muchgitsuchwow response and if everything ok, will close the ticket.
