### ISSUE TITLE
Feature request: add support for trivy and tflint

### ISSUE THREAD

**Issue by mm-chia** [tofuutils/tenv#210]
First off, many thanks for a maintaining such a useful tool!

It would like to know if you would consider adding support for these tools as well:

`trivy`: https://github.com/aquasecurity/trivy (moved from `tfsec`)
`tflint`: https://github.com/terraform-linters/tflint

They go hand in hand with Terraform/Tofu, widely used in CI together.
So it would be really nice if we can install them as well, using `tenv`!

best regards,

**Comment by dvaumoron** [comment]
Thanks for the suggestions, I will take a look

**Comment by kvendingoldo** [comment]
It goes a little bit outside of the original idea for managing Terraform/Tofu versions.
@dvaumoron @Nmishin @anastasiiakozlova245 do you think that it's reasonable?

**Comment by Nmishin** [comment]
@kvendingoldo I agree. Install `tflint` and `trivy` outside the scope of tenv because the main feature of tenv is that we can manage versions of tools in different ways. However,  for `tflint` and `trivy` we don't need to manage versions; we only need to install them, what can be done in many different ways.

**Comment by kvendingoldo** [comment]
yep, for example by asdf

**Comment by mm-chia** [comment]
thanks for the suggestion regarding asdf! I went that route.
best regards,
