### ISSUE TITLE
When using terraform format on stdin/stdout tenv output is included in the resulting output stream

### ISSUE THREAD

**Issue by archoversight** [tofuutils/tenv#63]
**Describe the bug**

**To Reproduce**
```
cat << EOF > versions.tf
/*
  Description: Required Terraform Versions
*/

terraform {
required_version = "1.5.7"

required_providers {
aws = {
source  = "hashicorp/aws"
version = "5.36.0"
    }
  }
}
EOF
cat versions.tf | terraform fmt -
```

Outputs:

```
No version files found for Terraform , fallback to latest-allowed strategy
Scan project to find .tf files
Found compatible version installed locally : 1.5.7
/*
  Description: Required Terraform Versions
*/

terraform {
  required_version = "1.5.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.36.0"
    }
  }
}
```

**Expected behavior**
`tenv` output is either suppressed or send to stderr instead. 

This is an issue when the terraform command is used as a filter, for example when using it to format files in Neovim or other editors or scripts where there may not be a valid file on disk or the formatter is run on a buffer instead.

**Screenshots**

**Environment (please complete the following information):**
- OS: macOS
- tofuenv version: tenv version v1.0.15

**Additional context**

**Comment by dvaumoron** [comment]
If you need a strict proxy behavior (without informative display), you can use TENV_QUIET=true

**Comment by kvendingoldo** [comment]
btw. don't you think that it will be a good idea to set TENV_QUIET=true by default, and in case if user want to see logs, he'll set this env variable

**Comment by dvaumoron** [comment]
I do not think so, that was the previous behavior and it has been criticized ( see #43 ).

The main remark was that when you launch a command without having installed any version, that's strange to wait without knowing what is happening, you wonder "is thing working or blocked ?". That's why, in most case having display seem better to me.

Beside that, I choose to add the quiet behavior to still be able to have a strict proxy behavior (just in case...).

**Comment by samuel-phan** [comment]
Here's my suggestion to fix this:

1. Send `tenv` messages to stderr instead of stdout.
2. Only display messages upon the download of a TF version. If the desired TF version is installed already, behave as a strict proxy command.

Rationale:

```
❯ terraform show --help
Resolved version from /Users/sphan02/.tenv/Terraform/version : 1.7.2
Usage: terraform [global options] show [options] [path]

  Reads and outputs a Terraform state or plan file in a human-readable
  form. If no path is specified, the current state will be shown.

Options:

  -no-color           If specified, output won't contain any color.
  -json               If specified, output the Terraform plan or state in
                      a machine-readable form.
```

The line ```Resolved version from /Users/sphan02/.tenv/Terraform/version : 1.7.2``` adds noise to the output for a `--help`.

Since the TF version is downloaded already, the command should respond quickly, so there's no need to add any extra text.

In case the user has a doubt on the used TF version, like for any other command, he/she will run `terraform --version`.

The problem I'm facing is specifically for this `terraform show -json my-plan > my-plan.json`, because `tenv` adds the line ```Resolved version from /Users/sphan02/.tenv/Terraform/version : 1.7.2```, the output file is NOT a JSON anymore and I'm having this error:

```
invalid character 'R' looking for beginning of value
```

**Comment by dvaumoron** [comment]
Your first point is what the PR change, your second point is more complex to do (must know which version is needed but have a lazy display until knowing if it is installed)

**Comment by dvaumoron** [comment]
The bug is fixed, I opened an other issue to manage the enhancement request
