### ISSUE TITLE
Allow setting of a fallback version

### ISSUE THREAD

**Issue by archoversight** [tofuutils/tenv#64]
**Is your feature request related to a problem? Please describe.**

I'd like to have the ability to set a fallback version that tenv will use if there is no version available or no version in .tf files.

This way if I start a new project, it acts as if I installed a particular version of terraform as the default terraform on my system. This is also useful when scripting or things of that nature.

Right now if I use:

```
tfenv tf use 1.5.7
```

It overrides detecting the versions from my `versions.tf` files, which makes it harder to switch between different projects that use different versions of terraform (especially due to a hard requirement to version pin software versions). 

**Describe the solution you'd like**

```
tfenv tf use --fallback 1.5.7

mkdir ~/tmptenvtest
cd ~/tmptenvtest
terraform -v
cd ~
rmdir ~/tmptenvtest
```

Would show terraform version 1.5.7 is in use, even-though there is no files in that directory.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by dvaumoron** [comment]
The current fallback is latest version, could it fit your purpose ? I guess new project can have requirement in companies, however despite #39, without more though reorganize thing as you ask would lead to weird code.

Moreover, is it really needed to separate the current `use` behavior and the asked fallback behavior ? Or does the version specified by `use` command should be checked after the scan for .tf files all the time ?

**Comment by dvaumoron** [comment]
Other idea :

`echo latest-allowed > .terraform-version`

In the project needing detection will allow to ignore the general case setted with `use`.

**Comment by orbitz** [comment]
I think using an environment variable, like in https://github.com/tofuutils/tofuenv/pull/41 would make the most sense.  This way there can be a fallback version per run of the command.

**Comment by dvaumoron** [comment]
Adding a second env var to choose version seem strange to me, there is already one, however the existing one force the version and skip other mechanism

**Comment by orbitz** [comment]
The current environment variable is to set the version, a fallback would be what to choose if no other information is found, they serve different functions.  We use this quite commonly in Terrateam: users specify the version to use unless a directory specifically overrides it.

**Comment by dvaumoron** [comment]
I will add TOFUENV_TOFU_DEFAULT_VERSION, TFENV_TERRAFORM_DEFAULT_VERSION and TG_DEFAULT_VERSION (with latest as default value to keep the current behavior when not set).

I must though on a proper way to handle corner case (manage special behavior and avoid infinite recursion).

**Comment by orbitz** [comment]
Great.  Once this is in I can dump all the other version control tools and switch to tenv!

Which special cases are you thinking that would cause infinite recursion?

**Comment by dvaumoron** [comment]
Any special behavior without result like "~> 2.0.0" could lead to this kind of problem falling back to itself again and again.

**Comment by orbitz** [comment]
I still don't understand.  It's just a fallback version, right?  So it's used in the algorithm to determine the version.  What part of version resolution is recurisve?

**Comment by dvaumoron** [comment]
Exemple : You have no .tf file, so `latest-allowed` fallback, if the fallback is a contraint like "~> 2.0.0", **tenv** will search locally then remotely, if there is no result, as this constraint is the fallback, that cause an infinite recursion.

**Comment by orbitz** [comment]
Ok, I don't know how the version resolving works in tenv.  In tfenv and tofuenv it is non-recursive.

**Comment by orbitz** [comment]
I will be very happy once this is implemented, though!  Looking forward to switching to tenv.

**Comment by dvaumoron** [comment]
Why https://github.com/tofuutils/tenv/issues/64#issuecomment-1946091220 is not enough ?

If you use `latest-allowed`, why did a fallback to `latest` does not fit your purpose ? You have no constraint so `latest` is a logical choice.

After thinking on the feature request, I do not get why is it useful ? If you do not want to use some Terraform version (because of licence change or any other reason), `latest-allowed` alone  is too dangerous (if your .tf files does not contains the correct contraint). Using an artifactory proxy to block downloading of prohibited versions would be safer.

**Comment by Nmishin** [comment]
I think the original issue about that tenv don't detect version from .tf file:
```
$ tenv --version
tenv version v1.1.1

$ cat versions.tf 
terraform {
  required_version = "1.6.0"
}

$ tenv tf detect
Terraform 1.3.0 will be run from this directory.
```

Also, I think I understand what @orbitz says - for now we can set default version only for explicitly call `tenv tf use 1.3.0` and override that version via `.terraform-version` file.
But @orbitz you want to have ability to specify env variable instead of calling `tenv tf use 1.3.0`, right?

**Comment by dvaumoron** [comment]
I just tested again with your versions.tf example (this time under Windows (not taken time to switch computer)) and that work as expected (despite Antivirus warning). 

Beside that forcing the use of a version is already available (with TFENV_TERRAFORM_VERSION for Terraform)

The original request from archoversight `tenv tf use` was : 

>  It overrides detecting the versions from my versions.tf 

So he need at least a change in the priority order to fallback to the value configured with `use` after the detection from .tf file (unsure because he did not reply to the answer).

However after a deeper look at [tofuutil/tofuenv#41](https://github.com/tofuutils/tofuenv/pull/41), it seems that the request from orbitz is almost not related to the initial one, and far simpler...

If orbitz goal is to have the resolution order :
- TFENV_TERRAFORM_VERSION 
- .terraform-version file
- .tfswitchrc file
- TFENV_TERRAFORM_DEFAULT_VERSION 
- $HOME/.tenv/Terraform/version file
- latest (`tenv tf install` command) or latest-allowed (`tenv tf detect` or `terraform` proxy)

That's easy (because there is no recursion risk)

**Comment by orbitz** [comment]
Yes that is my request, and that is my understanding of this issue as well.

**Comment by dvaumoron** [comment]
I added TOFUENV_TOFU_DEFAULT_VERSION, TFENV_TERRAFORM_DEFAULT_VERSION and TG_DEFAULT_VERSION (but not the README part yet).

The .tf files scanning occurs only for the `latest-allowed` behavior, so i think the initial request does not correspond to your request.

**Comment by archoversight** [comment]
My primary requirement is that I need to have a set version of terraform for running formatting in editors and places like that where there may not be a valid working directory, may not even be a `versions.tf` or a `.terraform-version`, and the code to be formatted is passed on stdin to the `terraform` command.

So I set that terraform 1.5.7 because at work I am not allowed to use BSL licensed terraform, so `latest-allowed` downloading anything `>1.5.7` would be an issue for me.

Then when I was working on a project that still pinned to version 1.3.x of terraform by having that in `versions.tf` it would try to use version 1.5.7 instead. That's why I wanted a fallback because `use 1.5.7` seemed to hard-pin it, it sounds like that is not true, in that you can override it with `.terraform-version` but I don't want to track the version in two different locations (namely `versions.tf` and `.terraform-version`) especially when other people may not be using `tenv` as they are on more locked down bastion hosts where the version of terraform is provided and they are not working across multiple code bases with different versions of terraform pinned.

**Comment by archoversight** [comment]
I expect the following resolution:

1. .terraform-version
2. *.tf files
3. tenv use version

Would make sense to me. That way the version set with tenv use would be the fallback in case there is nothing auto-detected.

**Comment by dvaumoron** [comment]
> So I set that terraform 1.5.7 because at work I am not allowed to use BSL licensed terraform, so `latest-allowed` downloading anything `>1.5.7` would be an issue for me.

So, I was right and as I said :

> `latest-allowed` alone is too dangerous

In my opinion, adding a possibility like `tenv tf constraint "<= 1.5.7"` to ensure to have the constraint "<= 1.5.7" whatever is found in .tf files (even if there is no such files) is better. Because letting the default `latest-allowed` could lead to using a non compliant version before the fallback to `latest` (or 1.5.7 with your proposition).

**Comment by orbitz** [comment]
So what is the resolution order?  I would expect something like:

1. Explicit version specification (tfenv use or version env variable)
2. `.terraform-version` or `.opentofu-version`.
3. `required-version` in a `.tf` file.
4. DEFAULT constraint otherwise.

Is that correct?  The README update in the change is not quote clear on the resolution order.

Thank you!

**Comment by dvaumoron** [comment]
With the last refactoring, the resolution order for Terraform is :

- TFENV_TERRAFORM_VERSION environment variable
- `.terraform-version` file
- `.tfswitchrc` file
- `terraform_version_constraint` from `terragrunt.hcl` file
- `terraform_version_constraint` from `terragrunt.hcl.json` file
- TFENV_TERRAFORM_DEFAULT_VERSION environment variable
- `$HOME/.tenv/Terraform/version` file (can be written with `tenv tf use`)
- `latest` (`tenv tf install `command) or `latest-allowed` (`tenv tf detect` command or `terraform` proxy)

where `required_version` from `*.tf` or `*.tf.json` files are searched in the `latest-allowed` behavior resolution, which fallback to `latest` when no constraint are found.

Moreover it is now possible to add a default constraint with TFENV_TERRAFORM_DEFAULT_CONSTRAINT environment variable or `$HOME/.tenv/Terraform/constraint` file (can be written with `tenv tf constraint`). The default constraint is added while using `latest-allowed`, `min-required` or custom constraint. A default constraint with `latest-allowed` or `min-required` will avoid the fallback to `latest` when there is no `*.tf` or `*.tf.json` files.

For most use case, `tenv tf constraint "<= 1.5.7"` will ensure no BSL version will be used, but it can lead to "no compatible version found" message with uncompatible constraint like "~> 1.6.0" (obviously no version check the two constraints).

I will update the README to explicit the current resolution order for each tool.

**Comment by orbitz** [comment]
Wow this is great!

**Comment by giner** [comment]
It would be more convenient and obvious if the required_versions were considered before any defaults. Here is a proposal https://github.com/orgs/tofuutils/discussions/7
